<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="YY1_IF_PAYMENT_DOCUMENTS">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="YY1_IF_PAYMENT_DOCUMENTSType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" nillable="false" name="ID" xmlns=""/>
                            <xs:element nillable="true" minOccurs="0" name="CoCode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="4"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" name="Clearing">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" name="DocRef">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="16"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" name="Assign">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="18"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" name="Cust">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:decimal" nillable="true" minOccurs="0" name="Amt" xmlns=""/>
                            <xs:element nillable="true" minOccurs="0" name="RefInv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="18"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element nillable="true" minOccurs="0" name="Src">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" xmlns="">
                                        <xs:maxLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
