name: Deploy CPI Artifacts Back to CPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: engswee/flashpipe:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy CPI package
        run: |
          flashpipe \
            --tmn-host "${{ secrets.DEV_TMN_HOST }}" \
            --oauth-host "${{ secrets.DEV_OAUTH_HOST }}" \
            --oauth-clientid "${{ secrets.DEV_CLIENT_ID }}" \
            --oauth-clientsecret "${{ secrets.DEV_CLIENT_SECRET }}" \
            deploy \
            --package-id "CPIPracticeflows" \
            --dir-artifacts "cpi-artifacts/CPIPracticeflows" \
            --deploy-policy "CREATE_OR_UPDATE"
