name: Free CPI Documentation

on:
  workflow_dispatch:
  push:
    paths:
      - "*.zip"

jobs:
  generate-docs:
    runs-on: self-hosted  # IMPORTANT

    steps:
      - uses: actions/checkout@v4

      - name: Run documentation generator
        run: |
          python3 generate_docs_free.py
